server.port=${PORT:8080}
spring.application.name=notification-platform

# Database ? injected by Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis ? injected by Railway
spring.data.redis.url=${SPRING_DATA_REDIS_URL}

# Mail ? injected by Railway
spring.mail.host=smtp.gmail.com
spring.mail.port=465
sendgrid.api.key=${SENDGRID_API_KEY}
mail.from=${MAIL_FROM}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Rate limiting
app.rate-limit.max-requests=10
app.rate-limit.window-seconds=60

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging
logging.level.com.notifplatform=INFO
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{20} - %msg%n
